### PR TITLE
fix: Fix empty lesson title bug

### LINKED ISSUE #310: User can submit empty lesson title in edit mode
### Issue Description

When you edit a lesson, you can click save even if the title is empty.

Add validation to the edit input just like when we create a new lesson

https://github.com/rotimi-best/classroomio/assets/31730715/026f52fa-9cb9-4e82-b6e5-e43e9d27d96c

### Steps to Reproduce

_No response_

### Expected Behavior

_No response_

### Current Behavior

_No response_

### Screenshots (optional)

_No response_

### Operating System [e.g., Windows 10]

_No response_

### Browser [e.g., Chrome, Firefox]

_No response_

### Environment (locally, production, selfhosted)

_No response_

### Please check the boxes that apply to this issue report.

- [ ] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

### PR DESCRIPTION
**Pull request by Chifez**
## What does this PR do?
This PR fixes the empty lesson bug 

Fixes #310 

https://github.com/rotimi-best/classroomio/assets/69228399/fa4db456-c357-4e31-b3fa-0fb71a5de7be

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- run on local host

### Required

- [x] Filled out the "How to test" section in this PR
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the ClassroomIO Docs if changes were necessary

### CODE REVIEW

File: apps/dashboard/src/routes/courses/[id]/+page.svelte [hunk 1]
```diff
@@ -227,76 +227,74 @@
...
-  <CourseContainer bind:courseId={data.courseId}>
-    <PageNav title={$t('course.navItem.news_feed.heading')} disableSticky={true}>
-      <slot:fragment slot="widget">
-        <RoleBasedSecurity allowedRoles={[1, 2]}>
-          <PrimaryButton
-            className="mr-2"
-            label={$t('course.navItem.news_feed.heading_button.title')}
-            onClick={() => ($isNewFeedModal.open = true)}
-          />
-        </RoleBasedSecurity>
```
Comment (rotimi-best) [inline apps/dashboard/src/routes/courses/[id]/+page.svelte]: @Chifez I actually just moved this RoleBasedSecurity within CourseContainer, I missed it when testing, see the commit [here](https://github.com/rotimi-best/classroomio/commit/57cfc32dae9182cc62b9b209795839da3a13c1e1#diff-994c13a27e07a62a27d277314623ead4acb6ba3af3b00e948ad8c186bae1d2ac)


Btw that's the issue I tweeted about. Rolebasedsecurity should not be over coursecontainer because coursecontainer fetches the course and group that Rolebasedsecurity depends on to render the roles.

That's what cause this blank page on prod after i deployed the lms customization feature.

image

Please revert the changes in this file

File: apps/dashboard/src/routes/courses/[id]/+page.svelte [hunk 2]
```diff
@@ -227,76 +227,74 @@
   $: initNewsFeed(data.courseId);
 
   $: setAuthor($group, $profile.id);
-
+  $: console.log('index page');
```
Comment (rotimi-best) [inline apps/dashboard/src/routes/courses/[id]/+page.svelte]: please remove

File: apps/dashboard/src/lib/components/Course/components/Navigation/index.svelte [hunk 3]
```diff
@@ -280,7 +280,7 @@
                       size="sm"
                       shape="rounded-full"
                     />
-                    <span>{item.title}</span>
+                    <span class="w-[70%] text-ellipsis line-clamp-2">{item.title}</span>
```
Comment (rotimi-best) [inline apps/dashboard/src/lib/components/Course/components/Navigation/index.svelte:283]: What's the reason for the 70%?

File: apps/dashboard/src/routes/courses/[id]/marks/+page.svelte [hunk 4]
```diff
@@ -90,94 +90,92 @@
...
-<RoleBasedSecurity allowedRoles={[1, 2, $currentOrg.customization.course.grading ? 3 : 0]}>
-  <CourseContainer bind:courseId={data.courseId}>
-    <PageNav title={$t('course.navItem.marks.title')} />
-
-    <PageBody width="w-full max-w-6xl md:w-11/12">
-      <div class="table rounded-md border border-gray-300 w-full">
-        <div class="flex items-center {borderBottomGrey}">
-          <div class="box flex items-center p-3">
-            <p class="dark:text-white w-40">{$t('course.navItem.marks.student')}</p>
+<CourseContainer bind:courseId={data.courseId}>
```
Comment (rotimi-best) [inline apps/dashboard/src/routes/courses/[id]/marks/+page.svelte]: @Chifez Please revert this change as well. I have fixed it on `main`

File: apps/dashboard/src/lib/components/Course/components/Lesson/store/lessons.ts [hunk 5]
```diff
@@ -4,6 +4,20 @@ import { createLesson, updateLesson, deleteLesson } from '$lib/utils/services/co
...
+  title: z.string().nonempty({ message: 'Title cannot be empty' }),
+  lesson_at: z.string().optional(),
+  call_url: z.string().nullable().optional(),
+  profile: z
+    .object({
+      id: z.string().optional()
+    })
+    .optional(),
+  is_unlocked: z.boolean()
+});
```
Comment (rotimi-best) [inline apps/dashboard/src/lib/components/Course/components/Lesson/store/lessons.ts]: @Chifez I think this validation is a duplicate

**Review by rotimi-best — CHANGES_REQUESTED** [review]

File: apps/dashboard/src/routes/courses/[id]/+page.svelte (hunk 1 above)
Comment (Chifez) [reply apps/dashboard/src/routes/courses/[id]/+page.svelte]: ah i see,noted

File: apps/dashboard/src/lib/components/Course/components/Navigation/index.svelte (hunk 3 above)
Comment (Chifez) [reply apps/dashboard/src/lib/components/Course/components/Navigation/index.svelte:283]: long lesson titles breaks away from the navbar, but his change makes it take up only 70% and then break into a new line
Screenshot (1084)

**Review by rotimi-best — APPROVED** [review]
LGTM!
