### PR TITLE
fix: date field bg-color in dark mode

### LINKED ISSUE #18: Lesson date on dark mode has a white background and white text
On dark mode make the date input on the lessons page to `bg-neutral-800` and `text-white`

Screenshot 2023-11-10 at 22 49 16

### PR DESCRIPTION
**Pull request by R4Rohit23**
This PR fixed #18 .

### Output
image

### CODE REVIEW

File: src/routes/courses/[id]/lessons/+page.svelte [hunk 1]
```diff
@@ -186,16 +187,10 @@
...
                 <div class="flex items-center lg:mb-0">
                   {#if lessonEditing === lesson.id}
-                    <input
-                      type="date"
-                      name="lesson-date-picker"
-                      class="p-2 my-2 rounded-md sm:w-[179px]"
-                      value={formatDate(lesson.lesson_at)}
-                      on:input={(e) => (lesson.lesson_at = e.target.value)}
-                    />
+                    <DateField value={formatDate(lesson.lesson_at)} className="p-2 my-2 rounded-md sm:w-[179px] dark:bg-neutral-800 dark:text-white" label="" placeholder="" onChange={(e) => (lesson.lesson_at = e.target.value)}/>
```
Comment (rotimi-best) [inline src/routes/courses/[id]/lessons/+page.svelte]: @R4Rohit23 You would need to use prettier to format the code.

Do you have prettier setup?

File: src/routes/courses/[id]/lessons/+page.svelte [hunk 2]
```diff
@@ -186,16 +187,10 @@
...
                   {:else}
                     <div class="flex mb-2">
-                      <Calendar size={20} class="carbon-icon text-gray-400 dark:text-white" />
+                      <Calendar size={20} class="carbon-icon text-gray-400 dark:text-whit" />
```
Comment (rotimi-best) [inline src/routes/courses/[id]/lessons/+page.svelte]: Please undo this change 😊

File: .env.example [hunk 3]
```diff
@@ -1,27 +0,0 @@
-# Supabase setup - Required
```
Comment (rotimi-best) [inline .env.example]: @R4Rohit23 You shouldn't delete this file.

Please can you restore it?

**Review by rotimi-best — CHANGES_REQUESTED** [review]
Thanks for the work @R4Rohit23.

Left you some comments I'd like you to look into, thanks

**Comment by rotimi-best** [comment]
@R4Rohit23 Thanks for the work 😃, Congrats on fixing your first issue.
