### PR TITLE
fix: Made the text input of course description in certificate visible 

### LINKED ISSUE #252: Certificate Text area input not visible in dark mode
### Issue Description

Contents of the text area for the course description in the certificate is not visible in dark mode 

### Steps to Reproduce

run the dashboard project on local host, create course and navigate to the certificates page in dark mode 

### Expected Behavior

course description text or placeholder should be visible in dark mode

### Current Behavior

course description text or placeholder is not visible in dark mode

### Screenshots (optional)

Screenshot (978)
Screenshot (979)

### Operating System [e.g., Windows 10]

_No response_

### Browser [e.g., Chrome, Firefox]

_No response_

### Environment (locally, production, selfhosted)

_No response_

### Please check the boxes that apply to this issue report.

- [ ] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

### PR DESCRIPTION
**Pull request by Chifez**
## What does this PR do?
This PR makes the text input of course description in certificate visible 

Fixes #252 

Screenshot (1002)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- run on localhost 
### Required

- [x] Filled out the "How to test" section in this PR
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the ClassroomIO Docs if changes were necessary

### CODE REVIEW

File: apps/dashboard/src/lib/components/Course/components/Ceritficate/Design.svelte [hunk 1]
```diff
@@ -92,7 +92,7 @@
           <TextArea
             rows={6}
             placeholder="a little description about the course"
-            bgColor="bg-gray-100"
+            bgColor="bg-gray-100 dark:text-black"
```
Comment (rotimi-best) [inline apps/dashboard/src/lib/components/Course/components/Ceritficate/Design.svelte]: @Chifez Is there a reason we are adding a bgColor here? What's wrong with the default?

**Review by rotimi-best — CHANGES_REQUESTED** [review]

File: apps/dashboard/src/lib/components/Course/components/Ceritficate/Design.svelte (hunk 1 above)
Comment (Chifez) [reply apps/dashboard/src/lib/components/Course/components/Ceritficate/Design.svelte]: i think it was too light it had a bg-gray-50, also the default bgColor prop holds a default dark:text-white class and that is why the text area content is not visible on dark mode so i override it by adding the dark:text-black class

Comment (Chifez) [reply apps/dashboard/src/lib/components/Course/components/Ceritficate/Design.svelte]: but instead of that i just pushed an update where the className prop holds a tailwind class of dark:text-black instead of it being on the bgColor prop

Comment (rotimi-best) [reply apps/dashboard/src/lib/components/Course/components/Ceritficate/Design.svelte]: No you don't get my point.

The TextArea component should handle dark mode and how it looks, not that you need to make it work for only this particular case.

All you needed to do was just remove the `bgColor`

Comment (rotimi-best) [reply apps/dashboard/src/lib/components/Course/components/Ceritficate/Design.svelte]: @Chifez 

## Dark mode
image

## Light mode
image

**Review by rotimi-best — APPROVED** [review]
