### PR TITLE
fix: validation of username and fullname

### LINKED ISSUE #397: Incorrect Validation of Username and FullName
### Issue Description

If  either the username or the fullname is empty, the data has been saved successfully.

https://github.com/user-attachments/assets/f56abcc6-c911-4ebc-af97-73097366dc98

### Steps to Reproduce

go to settings, 
make username or full name empty,
save the changes

### Expected Behavior

The interface should show the error if the username or the full name is empty,

### Current Behavior

The user data has saved successfully

### Screenshots (optional)

_No response_

### Operating System [e.g., Windows 10]

MacOs

### Browser [e.g., Chrome, Firefox]

Safari

### Environment (locally, production, selfhosted)

Production

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

### PR DESCRIPTION
**Pull request by smritidoneria**
## What does this PR do?

The pr allows the validation of username and full name correctly

Fixes #397

https://github.com/user-attachments/assets/4af21d8b-cfd4-472d-a4c5-b0b87c4c1683

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
go to settings, make the username and full name as empty
- Test B

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the ClassroomIO Docs if changes were necessary

### CODE REVIEW

File: apps/dashboard/src/lib/components/Org/Settings/Profile.svelte [hunk 1]
```diff
@@ -13,21 +13,29 @@
...
+    email: '',
+    username: '',
+    fullname: ''
+  };
 
   async function handleUpdate() {
-    errors = updateProfileEmailValidation($profile.email)
+    errors.email = updateProfileEmailValidation($profile.email).email || '';
+    errors.username = updateProfileUsernameValidation($profile.username).username || '';
+    errors.fullname = updateProfileFullnameValidation($profile.fullname).fullname || '';
```
Comment (rotimi-best) [inline apps/dashboard/src/lib/components/Org/Settings/Profile.svelte]: You shouldn't create a validation for each field.

Please look at how we do validation here and if possible reuse it.

https://github.com/rotimi-best/classroomio/blob/main/apps/dashboard/src/routes/onboarding/%2Bpage.svelte#L126

File: apps/dashboard/src/lib/utils/functions/validator.js [hunk 2]
```diff
@@ -2,6 +2,7 @@ import isNumber from 'lodash/isNumber';
 import z from 'zod';
 import { validateEmail } from './validateEmail';
 import { t } from '$lib/utils/functions/translations';
+import { user } from '../store/user';
```
Comment (rotimi-best) [inline apps/dashboard/src/lib/utils/functions/validator.js]: Why is this imported here?

**Review by rotimi-best — CHANGES_REQUESTED** [review]
Thanks for the PR.

You fundamentally need to change how you validate the fields

**Review by rotimi-best — APPROVED** [review]
LGTM
