### PR TITLE
fix: Duplicate Invite Issues.

### LINKED ISSUE #88: Duplicate Invite Issue
### Issue Description

After sending an invite to a specific user, attempting to send another invite using the same credentials does not return the expected error message indicating that the user already exists. The system shows the duplicate user details, and even after the user has accepted the invite, the system can still regenerate a new invite.

Screenshot 2023-12-08 at 16 34 54

### Steps to Reproduce

Log in to the application.
Navigate to the "Settings" feature.
Navigate to the invite section.
Send an invite to a specific user by entering their email address.
Attempt to send another invite to the same user with the same credentials.

### Expected Behavior

An error message should be displayed, indicating that the user already exists and preventing the duplicate invite.
The absence of the error message may lead to confusion and potential duplicate user entries.

### Current Behavior

No error message is shown, and the application allows the sending of a duplicate invite using the same credentials.

### Screenshots (optional)

_No response_

### Operating System [e.g., Windows 10]

_No response_

### Browser [e.g., Chrome, Firefox]

_No response_

### Environment (locally, production, selfhosted)

_No response_

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

### PR DESCRIPTION
**Pull request by R4Rohit23**
## What does this PR do?

After sending an invite to a specific user, attempting to send another invite using the same credentials return the expected error message indicating that the user already exists. 

Fixes #88 

## Output
https://jam.dev/c/8a47ed9a-81e9-4258-89b6-67ce163eca9a

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?
1. Log in to the application.
2. Navigate to the "Settings" feature.
3. Navigate to the invite section.
4. Send an invite to a specific user by entering their email address.
5. Attempt to send another invite to the same user with the same credentials.

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### CODE REVIEW

File: apps/dashboard/src/lib/components/Org/Settings/TeamMembers.svelte [hunk 1]
```diff
@@ -38,7 +38,17 @@
...
+
+      const { data, error } = await supabase.from('organizationmember').select('email');
+
+      const emailExists = data?.some((obj) => obj.email === email);
+
+      if (emailExists) {
+        snackbar.error("Email Already Exists");
+        isLoading = false;
+        return;
+      } else {
```
Comment (rotimi-best) [inline apps/dashboard/src/lib/components/Org/Settings/TeamMembers.svelte]: You shouldn't pull from the whole database of `organizationmember` in the database just to find if the email exists.

What you should do is to check if the email entered by the user is included in the array of emails rendered on the UI. We already have a list of emails that belong to that organisation - `$orgTeam`.

https://github.com/rotimi-best/classroomio/blob/main/apps/dashboard/src/lib/components/Org/Settings/TeamMembers.svelte#L161C3-L166C3

You should do something like this:

```js
const doesEmailExist = $orgTeam.some(teamMember => teamMember.email.toLowerCase() === email.toLowerCase())
```

**Review by rotimi-best — CHANGES_REQUESTED** [review]
Thanks for the PR @R4Rohit23 🙏 

Requested a core change, thanks ☺️

**Comment by rotimi-best** [comment]
Tested it and it works 🎉 


Screenshot 2023-12-11 at 03 48 02
